// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"yuumi-movie/app/media/admin/internal/biz"
	"yuumi-movie/app/media/admin/internal/conf"
	"yuumi-movie/app/media/admin/internal/data"
	"yuumi-movie/app/media/admin/internal/server"
	"yuumi-movie/app/media/admin/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	mediaRepo := data.NewMediaRepo(dataData, logger)
	mediaUsecase := biz.NewMediaUsecase(mediaRepo, logger)
	mediaAdminService := service.NewMediaAdminService(mediaUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, mediaAdminService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
