// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/media/admin/v1/media_admin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMediaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Desc   string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Cover  string `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Title  string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Areas  string `protobuf:"bytes,5,opt,name=areas,proto3" json:"areas,omitempty"`
	Actors string `protobuf:"bytes,6,opt,name=actors,proto3" json:"actors,omitempty"`
	Styles string `protobuf:"bytes,7,opt,name=styles,proto3" json:"styles,omitempty"`
}

func (x *CreateMediaReq) Reset() {
	*x = CreateMediaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_media_admin_v1_media_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMediaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMediaReq) ProtoMessage() {}

func (x *CreateMediaReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_media_admin_v1_media_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMediaReq.ProtoReflect.Descriptor instead.
func (*CreateMediaReq) Descriptor() ([]byte, []int) {
	return file_api_media_admin_v1_media_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMediaReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateMediaReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateMediaReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *CreateMediaReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMediaReq) GetAreas() string {
	if x != nil {
		return x.Areas
	}
	return ""
}

func (x *CreateMediaReq) GetActors() string {
	if x != nil {
		return x.Actors
	}
	return ""
}

func (x *CreateMediaReq) GetStyles() string {
	if x != nil {
		return x.Styles
	}
	return ""
}

type CreateMediaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateMediaReply) Reset() {
	*x = CreateMediaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_media_admin_v1_media_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMediaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMediaReply) ProtoMessage() {}

func (x *CreateMediaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_media_admin_v1_media_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMediaReply.ProtoReflect.Descriptor instead.
func (*CreateMediaReply) Descriptor() ([]byte, []int) {
	return file_api_media_admin_v1_media_admin_proto_rawDescGZIP(), []int{1}
}

var File_api_media_admin_v1_media_admin_proto protoreflect.FileDescriptor

var file_api_media_admin_v1_media_admin_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0xa6, 0x01, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x72, 0x65,
	0x61, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x72, 0x65, 0x61, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x79, 0x6c, 0x65,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x73, 0x22,
	0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x32, 0x5f, 0x0a, 0x0a, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x12, 0x51, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x12, 0x1e, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71,
	0x1a, 0x20, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x23, 0x5a, 0x21, 0x79, 0x75, 0x75, 0x6d, 0x69, 0x2d, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_media_admin_v1_media_admin_proto_rawDescOnce sync.Once
	file_api_media_admin_v1_media_admin_proto_rawDescData = file_api_media_admin_v1_media_admin_proto_rawDesc
)

func file_api_media_admin_v1_media_admin_proto_rawDescGZIP() []byte {
	file_api_media_admin_v1_media_admin_proto_rawDescOnce.Do(func() {
		file_api_media_admin_v1_media_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_media_admin_v1_media_admin_proto_rawDescData)
	})
	return file_api_media_admin_v1_media_admin_proto_rawDescData
}

var file_api_media_admin_v1_media_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_media_admin_v1_media_admin_proto_goTypes = []interface{}{
	(*CreateMediaReq)(nil),   // 0: media.admin.v1.CreateMediaReq
	(*CreateMediaReply)(nil), // 1: media.admin.v1.CreateMediaReply
}
var file_api_media_admin_v1_media_admin_proto_depIdxs = []int32{
	0, // 0: media.admin.v1.MediaAdmin.CreateMedia:input_type -> media.admin.v1.CreateMediaReq
	1, // 1: media.admin.v1.MediaAdmin.CreateMedia:output_type -> media.admin.v1.CreateMediaReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_media_admin_v1_media_admin_proto_init() }
func file_api_media_admin_v1_media_admin_proto_init() {
	if File_api_media_admin_v1_media_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_media_admin_v1_media_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMediaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_media_admin_v1_media_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMediaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_media_admin_v1_media_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_media_admin_v1_media_admin_proto_goTypes,
		DependencyIndexes: file_api_media_admin_v1_media_admin_proto_depIdxs,
		MessageInfos:      file_api_media_admin_v1_media_admin_proto_msgTypes,
	}.Build()
	File_api_media_admin_v1_media_admin_proto = out.File
	file_api_media_admin_v1_media_admin_proto_rawDesc = nil
	file_api_media_admin_v1_media_admin_proto_goTypes = nil
	file_api_media_admin_v1_media_admin_proto_depIdxs = nil
}
