server:
  http:
    addr: 0.0.0.0:8100
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9100
    timeout: 1s
data:
  database:
    dsn: "root:localdb001@tcp(127.0.0.1:3306)/yuumi?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
jwt:
  secret: "kratos"